### ISSUE TITLE
"failing is not always an error" behavior when running command

### ISSUE THREAD

**Issue by acasadevall** [open-s4c/benchkit#100]
Reasonably I see default behavior in `shell_out` is try to execute and check if error code is not part of the already ignored ret cases `ignore_ret_codes`. 

In general is a bad practice, but having something like "ignore all errors" could be useful specially when you do not have clear info about all possible errors in the test bench or you are just testing. 

**Possible implementation:**
```
...
try:
    output = subprocess.check_output(...)
except subprocess.CalledProcessError as err:
    retcode = err.returncode
    if retcode not in ignore_ret_codes and not ignore_all_errors:
            raise err
...
```

Besides, in case of error (ignored or not) I think it would be good to trace it with corresponding cmd and with their stderr output if any.

**Comment by apaolillo** [comment]
Fixed by #108
