### ISSUE TITLE
issue in running perf remotely 

### ISSUE THREAD

**Issue by Nimaro76** [open-s4c/benchkit#20]
the perf execution through wrapper_perf of a remote platform through the campaign doesn't work as it tries to write the output to a path in local machine after executing on the remote platform 
error : subprocess.CalledProcessError: Command '['ssh', '-t', 'ubuntu@10.42.0.138', 'cd /home/ubuntu/Performan_evaluation/tasks/build && /usr/bin/perf stat -e branch-misses,cache-misses,cpu-cycles --output "/home/nima/Performan_evaluation/benchkit/benchkit/examples/leveldb/kit/results/benchmark_nima-Precision-5480_kria_camera_campaign_20240508_132947_224373/benchmark duration seconds-1/run-1/perf-stat.txt" ./CameraProcessing 1']' returned non-zero exit status 255.

**Comment by apaolillo** [comment]
@RobbeDGreef fixed that by implementing copyto/copyfrom hosts in #25
