### ISSUE TITLE
os.getlogin() error on wsl

### ISSUE THREAD

**Issue by aaronbog** [open-s4c/benchkit#65]
The post_run_hook_flamegraph errors with "**OSError: [Errno 6] No such device or address**" on Windows Subsystem for Linux

This is due to the os.getlogin() call

**Comment by apaolillo** [comment]
thanks for flagging. Do you have a PR that solves that? Or is it part of the general PR still?

**Comment by aaronbog** [comment]
I am working on a PR but am considering two solutions and thus doing some extra research on which would be better

**Comment by apaolillo** [comment]
ok, do not hesitate to call me if you want to discuss that with me
